services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: mrsdb
      POSTGRES_USER: mrsuser
      POSTGRES_PASSWORD: mrspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mrsapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrsapi_container
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./movie_reservation/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=mrsdb
      - DB_USER=mrsuser
      - DB_PASS=mrspassword

volumes:
  redis_data:
  postgres_data: