# Generated by Django 5.1.5 on 2025-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDirectory',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=75)),
                ('rating', models.CharField(max_length=75)),
                ('release_date', models.DateField(max_length=75)),
            ],
        ),
    ]
