# Generated by Django 5.1.5 on 2025-02-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=100)),
                ('duration', models.DurationField(help_text='Duration of the movie (HH:MM:SS format)')),
                ('rating', models.CharField(max_length=75)),
                ('release_date', models.DateField(max_length=75)),
            ],
        ),
    ]
