# Generated by Django 5.1.5 on 2025-03-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedirectory',
            old_name='rating',
            new_name='genre',
        ),
    ]
