# Generated by Django 5.1.5 on 2025-02-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        ('Movie', '0003_alter_moviedirectory_duration'),
        ('Theatre', '0006_remove_seatmaster_seatclass_seatmaster_seatcol_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='showdirectory',
            constraint=models.UniqueConstraint(fields=('screenId', 'dateTime', 'showTypeId'), name='unique_show_per_screen_per_date'),
        ),
    ]
