# Generated by Django 5.1.5 on 2025-02-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_SeatType',
            fields=[
                ('seatTypeId', models.IntegerField(choices=[(1, 'Regular'), (2, 'Premium')], default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDirectory',
            fields=[
                ('screenId', models.AutoField(primary_key=True, serialize=False)),
                ('screenNum', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TheatreDirectory',
            fields=[
                ('theatreId', models.AutoField(primary_key=True, serialize=False)),
                ('theatreName', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=100)),
                ('locationCity', models.CharField(max_length=75)),
                ('locationState', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMaster',
            fields=[
                ('seatId', models.AutoField(primary_key=True, serialize=False)),
                ('seatName', models.CharField(max_length=10)),
                ('seatPrice', models.IntegerField()),
                ('seatRow', models.CharField(default='zx', max_length=2)),
                ('seatCol', models.IntegerField(default=0)),
                ('screenId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.screendirectory')),
                ('seatTypeId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Theatre.c_seattype')),
            ],
        ),
        migrations.AddField(
            model_name='screendirectory',
            name='theatreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.theatredirectory'),
        ),
    ]
