# Generated by Django 5.1.5 on 2025-02-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0002_rename_directory_theatredirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenDirectory',
            fields=[
                ('screenId', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('screenNum', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('theatreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.theatredirectory')),
            ],
        ),
        migrations.CreateModel(
            name='SeatMaster',
            fields=[
                ('SeatId', models.AutoField(primary_key=True, serialize=False)),
                ('SeatName', models.CharField(max_length=10)),
                ('SeatClass', models.CharField(max_length=75)),
                ('SeatPrice', models.IntegerField()),
                ('screenId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.screendirectory')),
            ],
        ),
    ]
