# Generated by Django 5.1.5 on 2025-02-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0003_screendirectory_seatmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screendirectory',
            name='DateTime',
        ),
    ]
