# Generated by Django 5.1.5 on 2025-02-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0004_remove_screendirectory_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_SeatType',
            fields=[
                ('seatTypeId', models.IntegerField(choices=[(1, 'Regular'), (2, 'Premium')], default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='seatmaster',
            old_name='SeatClass',
            new_name='seatClass',
        ),
        migrations.RenameField(
            model_name='seatmaster',
            old_name='SeatId',
            new_name='seatId',
        ),
        migrations.RenameField(
            model_name='seatmaster',
            old_name='SeatName',
            new_name='seatName',
        ),
        migrations.RenameField(
            model_name='seatmaster',
            old_name='SeatPrice',
            new_name='seatPrice',
        ),
        migrations.AddField(
            model_name='seatmaster',
            name='seatTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Theatre.c_seattype'),
        ),
    ]
