# Generated by Django 5.1.5 on 2025-02-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0005_c_seattype_rename_seatclass_seatmaster_seatclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatmaster',
            name='seatClass',
        ),
        migrations.AddField(
            model_name='seatmaster',
            name='seatCol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatmaster',
            name='seatRow',
            field=models.CharField(default='zx', max_length=2),
        ),
    ]
